[project]
name = "web"
revision = "1.0"
extends = ["../../secretspec.toml"]

[profiles.default]
VITE_SERVER_URL = { description = "Server URL", required = true }
VITE_PUBLIC_POSTHOG_HOST = { description = "Posthog host", required = false }
VITE_PUBLIC_POSTHOG_KEY = { description = "Posthog key", required = false }

[profiles.local]
VITE_SERVER_URL = { default = "http://localhost", ref = { item = "scottystack/local/web", field = "VITE_SERVER_URL" } }
VITE_PUBLIC_POSTHOG_HOST = { ref = { item = "scottystack/local/web", field = "VITE_PUBLIC_POSTHOG_HOST" } }
VITE_PUBLIC_POSTHOG_KEY = { ref = { item = "scottystack/local/web", field = "VITE_PUBLIC_POSTHOG_KEY" } }
