[project]
name = "scottystack"
revision = "1.0"

[providers]
bao = "openbao://bao.scottylabs.org/labrador"

[profiles.default.defaults]
providers = ["bao"]

[profiles.local.defaults]
providers = ["bao"]
