[project]
name = "db"
revision = "1.0"
extends = ["../../secretspec.toml"]

[profiles.default]
DATABASE_URL = { description = "Database connection string", required = true }

[profiles.local]
DATABASE_URL = { default = "postgresql://postgres:donotuseinprod@postgres:5432/scottystack", ref = { item = "scottystack/local/server", field = "DATABASE_URL" } }
